<a href="https://colab.research.google.com/github/francisfernande/Numpy/blob/main/numpy_practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
#create array
list = [1,2,3]
lst = np.array(list)

In [12]:
lst

array([1, 2, 3])

In [13]:
type(lst)

numpy.ndarray

In [14]:
# dimension on array (rows/cols)
lst.shape

(3,)

In [15]:
#2d array
nestd = np.array([[123,456],[789,654]])

In [16]:
nestd.shape

(2, 2)

In [17]:
x = np.array((1,2,3,4))

In [18]:
x.dtype

dtype('int64')

In [19]:
x.shape

(4,)

In [20]:
#array from scratch

In [21]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
np.arange(1,10,2).shape

(5,)

In [24]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [25]:
np.arange(50,1,-1)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2])

In [27]:
#equal 40 elements btw 1 to 20
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
#3D
np.zeros((2,8,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [32]:
#broadcasting operation
10 + np.ones((3,5))

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [33]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
#random no - uniform distrubution (0 to 1)
np.random.rand(2,3)

array([[0.25797061, 0.36518314, 0.51396304],
       [0.9720206 , 0.79532828, 0.99941555]])

In [38]:
#normal dist - mean =0 and sd =1
np.random.randn(5,3)

array([[-1.0750493 ,  0.31469607,  1.197667  ],
       [-0.49871381,  0.31059013, -0.67047358],
       [ 0.02373715, -0.31373578,  0.3962869 ],
       [ 0.22877495,  1.23311555, -1.85138618],
       [ 0.8134754 ,  0.11108433, -1.04853834]])

In [41]:
#random 3 elements
np.random.randint(1,10,3)

array([7, 2, 8])

In [43]:
np.random.randint(1,10,(3,3))

array([[7, 5, 2],
       [5, 6, 1],
       [6, 8, 2]])

In [46]:
#slicing
y = np.arange(0,11)

In [48]:
y[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
y[2:7]

array([2, 3, 4, 5, 6])

In [51]:
#universal function

arr1 = np.random.randint(1,100,(3,3))
arr2 = np.random.randint(20,100,(3,3))

In [52]:
arr1

array([[42, 18, 29],
       [17, 44, 26],
       [ 9, 57, 69]])

In [53]:
arr2

array([[78, 90, 21],
       [67, 28, 62],
       [90, 36, 34]])

In [54]:
arr1 + arr2

array([[120, 108,  50],
       [ 84,  72,  88],
       [ 99,  93, 103]])

In [55]:
arr1-arr2

array([[-36, -72,   8],
       [-50,  16, -36],
       [-81,  21,  35]])