<a href="https://colab.research.google.com/github/francisfernande/Numpy/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20.
#Replace all the elements in the third column with 1.


import numpy as np
arr1 = np.random.randint(1,20,size = (5,5))
arr1

array([[ 2, 13, 13,  9, 13],
       [ 7, 14, 14, 10,  4],
       [ 7, 11,  8, 11,  8],
       [ 7, 15,  6, 16,  6],
       [19,  9,  1, 11,  6]])

In [3]:
arr1[:, 2] = 1
arr1

array([[ 2, 13,  1,  9, 13],
       [ 7, 14,  1, 10,  4],
       [ 7, 11,  1, 11,  8],
       [ 7, 15,  1, 16,  6],
       [19,  9,  1, 11,  6]])

In [4]:
##2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0

array = np.arange(1, 17).reshape((4, 4))
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
np.fill_diagonal(array,0)
array

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

In [6]:
#. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

array = np.arange(1, 37).reshape((6, 6))
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [7]:
array[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [8]:
 #Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
 array = np.random.randint(1, 21, size=(5, 5))
 border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1]))
 border_elements

array([15, 13, 18, 10,  4,  6,  9, 19,  2,  9,  3, 20, 20, 18, 20, 20])

In [9]:
array

array([[15, 13, 18, 10,  4],
       [ 3, 10, 14, 19, 18],
       [20, 10,  2, 19, 20],
       [20, 20,  3, 12, 20],
       [ 6,  9, 19,  2,  9]])

In [10]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
arr1 = np.random.randint(1,11,size=(4,3))
arr2 = np.random.randint(1,11,size=(4,3))

In [11]:
# Perform element-wise operations
add =arr1+arr2
sub = arr1-arr2
div = arr1/arr2
multiply = arr1*arr2

In [12]:
add

array([[ 7,  3, 17],
       [20, 13, 15],
       [10,  8, 12],
       [11, 20, 10]])

In [13]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
array = np.arange(1,17).reshape((4,4))

In [14]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [15]:
r = np.sum(array,axis=1)
c = np.sum(array,axis=0)

In [16]:
r

array([10, 26, 42, 58])

In [17]:
c

array([28, 32, 36, 40])

In [18]:
#Create a NumPy array of shape (5, 5) filled with random integers.
#Compute the mean, median, standard deviation, and variance of the array.

In [19]:
aray = np.random.randint(1,78,size=(5,5))
print('original array')
print(aray)


original array
[[49 28 71 39 64]
 [ 8 14 27 27 31]
 [28 20 35 34 59]
 [ 7  2 10 68 30]
 [75 19 44 41 48]]


In [20]:
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Mean: 8.5
Median: 8.5
Standard Deviation: 4.6097722286464435
Variance: 21.25


In [21]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9.
#Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [22]:
ary = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(ary)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
mean = np.mean(ary)
std_dev = np.std(ary)
normalized_array = (ary - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [24]:
#Create a NumPy array of shape (3, 3) filled with random integers.
#Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [25]:
array = np.random.randint(1, 11, size=(3, 3))
row_array = np.random.randint(1, 11, size=(3,))
print("Original array:")
print(array)
print("1D array:")
print(row_array)

Original array:
[[5 7 9]
 [3 1 5]
 [1 5 4]]
1D array:
[6 7 3]


In [26]:
result = array + row_array
print("Resulting array:")
print(result)

Resulting array:
[[11 14 12]
 [ 9  8  8]
 [ 7 12  7]]


In [27]:
#Create a NumPy array of shape (3, 3) representing a matrix.
#Compute its determinant, inverse, and eigenvalues.

In [28]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

Original matrix:
[[9 6 6]
 [1 3 8]
 [4 6 4]]


In [29]:
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

Determinant: -192.00000000000017


In [30]:
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

Inverse:
[[ 0.1875     -0.0625     -0.15625   ]
 [-0.14583333 -0.0625      0.34375   ]
 [ 0.03125     0.15625    -0.109375  ]]


In [31]:
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Eigenvalues: [15.3837166   3.85436228 -3.23807889]


In [32]:
#Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [33]:
ar1 = np.random.randint(1,11,size=(2,3))
ar2 = np.random.randint(1,11,size=(3,2))

print("Array 1:")
print(ar1)
print("Array 2:")
print(ar2)

Array 1:
[[7 8 5]
 [4 9 6]]
Array 2:
[[ 1 10]
 [ 5  8]
 [ 5  3]]


In [34]:
result = np.dot(ar1, ar2)
result

array([[ 72, 149],
       [ 79, 130]])

In [35]:
#Create a NumPy array of shape (3, 3) with values from 1 to 9.
#Reshape the array to shape (1, 9) and then to shape (9, 1).

In [36]:
ary = np.arange(1,10).reshape((3,3))
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
new_ary = ary.reshape((1,9))
new_ary

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [38]:
latest_ary = new_ary.reshape((9,1))
latest_ary

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
#Create a NumPy array of shape (5, 5) filled with random integers.
#Flatten the array and then reshape it back to (5, 5).

In [40]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

Original array:
[[12 12  8 12 13]
 [10  6 18  8 13]
 [14 11  7 13 16]
 [ 8  4 17  2 10]
 [12 14 17  9 15]]


In [41]:
flattened_array = array.flatten()
print("Flattened array:")
print(flattened_array)

Flattened array:
[12 12  8 12 13 10  6 18  8 13 14 11  7 13 16  8  4 17  2 10 12 14 17  9
 15]


In [42]:
reshaped_array = flattened_array.reshape((5, 5))
print("Reshaped array:")
print(reshaped_array)

Reshaped array:
[[12 12  8 12 13]
 [10  6 18  8 13]
 [14 11  7 13 16]
 [ 8  4 17  2 10]
 [12 14 17  9 15]]


In [43]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[ 7 17 17 20 20]
 [17  1  4  3 14]
 [10 17 10 10 20]
 [10 17 13  9  2]
 [ 4  2  6 20 14]]
Corner elements:
[ 7 20  4 14]


In [44]:
array = np.random.randint(1, 21, size=(4, 4))
print("Original array:")
print(array)

# Use boolean indexing to set all elements less than 10 to 10
array[array < 10] = 10
print("Modified array:")
print(array)

Original array:
[[15 15  5 14]
 [ 7  2 18 15]
 [16 11 10 12]
 [16  1 12 17]]
Modified array:
[[15 15 10 14]
 [10 10 18 15]
 [16 11 10 12]
 [16 10 12 17]]


In [46]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]
